name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npm-actions/setup-node@v1
        with:
          node-version: "18"

      - run: npm install --frozen-lockfile
      - run: npm run ci
